name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    lint:
        runs-on: debian:12
        steps:
            - name: quality test
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm install -g --save-dev
            - name: Run eslint
              run: npx eslint src --fix
    
    sonarcloud:
        runs-on: debian:12
        needs: lint
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm install -g --save-dev
            - name: Run sonarcloud
              run: npx sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io
        
    trivy-scan:
        runs-on: debian:12
        needs: sonarcloud
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Docker
              uses: docker/setup-buildx-action@v2
            - name: Build Docker image
              run: docker build -t SpritShop .
            - name: Run Trivy scan
              run: trivy image SpritShop
    
    package:
        runs-on: debian:12
        needs: trivy-scan
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm install
            - name: Package the app
              run: npm pack 
    
artifact:
    runs-on: debian:12
    needs: package
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
              name: npm-package
              path: 'SpiritShop-1.0.0.tgz'

docker-build:
    runs-on: debian:12
    needs: artifact
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Setup Docker
          uses: docker/setup-buildx-action@v2
        - name: Build Docker image
          run: docker build -t SpritShop .
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Docker image
          run: docker push SpritShop
          


        
        